spring:
  data:
    mongodb:
      host: 10.228.131.21
      port: 27017
      database: test
      username: test
      password: test

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug