
spring:
  shardingsphere:
    datasource:
      names: m1, m2
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/coursedb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
        username: root
        password: 123456
      m2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/coursedb2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
        username: root
        password: 123456
    sharding:
      #广播表配置
      broadcast-tables: t_dict
      tables:
        t_dict:  #广播表配置
          key-generator:
            column: dict_id
            type: SNOWFLAKE

        course:    #分库分表
          actualDataNodes: m$->{1..2}.course_$->{1..2}
          key-generator:
            column: cid
            type: SNOWFLAKE

            #standard分片
          database-strategy:
            standard:
              sharding-column: cid
              precise-algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyPreciseDSShardingAlgorithm
              range-algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyRangeDSShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: cid
              precise-algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyPreciseTableShardingAlgorithm
              range-algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyRangeTableShardingAlgorithm

          #complex分片
#          database-strategy:
#            complex:
#              sharding-columns: cid, user_id
#              algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyComplexDSShardingAlgorithm
#          table-strategy:
#            complex:
#              sharding-columns: cid, user_id
#              algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyComplexTableShardingAlgorithm

          #hint分片
#          table-strategy:
#            hint:
#              algorithm-class-name: com.zxl.nacos.shardingspheredemo.algorithem.MyHintTableShardingAlgorithm





    # 读写分离配置，对应 YamlMasterSlaveRuleConfiguration 配置类
#    masterslave:
#      name: ms  # 名字，任意，需要保证唯一
#      master-data-source-name: ds-master # 主库数据源
#      slave-data-source-names: ds-slave-1, ds-slave-2 # 从库数据源

    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true

