#server:
#  port: 8075

spring:
  shardingsphere:
    datasource:
      names: ds-orders-0, ds-orders-1
      ds-orders-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zxl_orders_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
        username: root
        password: 123456
      ds-orders-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/zxl_orders_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
        username: root
        password: 123456
    sharding:
      default-data-source-name: ds-orders-0   #未配置分片规则的表将通过默认数据源定位
      tables:
        order_config:
#          actualDataNodes: ds-orders-0.order_config  #不分库不分表
          actualDataNodes: ds-orders-0.order_config_$->{[0,1]}  #不分库分表
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: pay_timeout
              algorithm-expression: order_config_$->{pay_timeout % 2}

        orders:    #分库分表
          actualDataNodes: ds-orders-0.orders_$->{[0,2,4,6]}, ds-orders-1.orders_$->{[1,3,5,7]}
          key-generator:
            column: id
            type: SNOWFLAKE
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds-orders-$->{user_id % 2}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: orders_$->{user_id % 8}


    # 读写分离配置，对应 YamlMasterSlaveRuleConfiguration 配置类
#    masterslave:
#      name: ms  # 名字，任意，需要保证唯一
#      master-data-source-name: ds-master # 主库数据源
#      slave-data-source-names: ds-slave-1, ds-slave-2 # 从库数据源

    props:
      sql:
        show: true
  main:
    allow-bean-definition-overriding: true




#mybatis:
#  mapper-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zxl.nacos.shardingspheredemo.entity
